# Setup
title: Burak's Blog
url: http://ergulburak.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-3DWR3NTPNX

# Specify the author for blog posts
author:
  name: Burak Ergül
  url: https://twitter.com/BurakERGUL_
  email: burakcan41@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /arsiv

  - title: Oyunlar
    url: /oyunlar

  - title: Hakkımda
    url: /hakkimda

